In [ ]:
!pip install transformers
!pip install torch
!pip install sentence-transformers

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [ ]:
#Spacy is a NLP Tool useful for getting dates, names, places, numbers etc from a sentence
import spacy
from spacy import displacy

NER = spacy.load("en_core_web_sm")
text="In August 1836, two real estate entrepreneurs—Augustus Chapman Allen and John Kirby Allen—from New York, purchased 6,642 acres (26.88 km2) of land along Buffalo Bayou with the intent of founding a city. The Allen brothers decided to name the city after Sam Houston, the popular general at the Battle of San Jacinto, who was elected President of Texas in September 1836. The great majority of slaves in Texas came with their owners from the older slave states. Sizable numbers, however, came through the domestic slave trade. New Orleans was the center of this trade in the Deep South, but there were slave dealers in Houston. Thousands of enslaved African-Americans lived near the city before the Civil War. Many of them near the city worked on sugar and cotton plantations, while most of those in the city limits had domestic and artisan jobs. In 1860 forty-nine percent of the city's population was enslaved. A few slaves, perhaps as many as 2,000 between 1835 and 1865, came through the illegal African trade. Post-war Texas grew rapidly as migrants poured into the cotton lands of the state. They also brought or purchased enslaved African Americans, whose numbers nearly tripled in the state from 1850 to 1860, from 58,000 to 182,566."
texty=tokenizer.tokenize(text)
text2=NER(text)
l=[]
for word in texty:
    if ((word in [chunk.text for chunk in text2.noun_chunks]) or (word in [token.lemma_ for token in text2 if token.pos_=="VERB"])):
      l.append(word)
print(l)

/usr/local/lib/python3.10/dist-packages/spacy/util.py:1740: UserWarning: [W111] Jupyter notebook detected: if using `prefer_gpu()` or `require_gpu()`, include it in the same cell right before `spacy.load()` to ensure that the model is loaded on the correct device. More information: http://spacy.io/usage/v3#jupyter-notebook-gpu
  warnings.warn(Warnings.W111)


['August', 'land', 'name', 'Houston', 'who', 'President', 'Texas', 'September', 'slaves', 'Texas', 'Houston', 'Thousands', 'them', 'those', 'slaves', 'Texas', 'migrants', 'They']


In [ ]:
import numpy as np
import pandas as pd
read_file = pd.read_excel ("queries.xlsx")

# Write the dataframe object
# into csv file
read_file.to_csv ("queries.csv",
                  index = None,
                  header=True)
read_file = pd.read_excel ("paragraphs.xlsx")

# Write the dataframe object
# into csv file
read_file.to_csv ("paragraphs.csv",
                  index = None,
                  header=True)


In [ ]:
dfp=pd.read_csv("paragraphs.csv", usecols=range(1,3))


In [ ]:
dfq=pd.read_csv("queries.csv")

In [ ]:
#Note : While executing the code blockas, sometimes you encounter error with number 5501. Run this cell atleast once and it goes away.
#Note : My guess is the reset index fixes the error.
dfp.drop_duplicates(inplace=True)

dfp = dfp.reset_index(drop=True)
print(dfp.head(10))
print(dfp.shape)
i=1
k=1
dfp.loc[0].iat[0]=dfp.loc[0].iat[0].upper()
while(i<dfp.shape[0]):
  if(pd.isna(dfp.loc[i].iat[0])):
    dfp.loc[i].iat[0]="1_MISCELLANEOUS"
  dfp.loc[i].iat[0]=dfp.loc[i].iat[0].upper()
  if(dfp.loc[i].iat[0]!=dfp.loc[i-1].iat[0]):
    k=k+1
  i=i+1
print(k)

print(dfp.loc[15559].iat[0])
print(dfp.shape)
dfp.sort_values(by = 'Keyword')

    Keyword                                               Text  \
0  ZHEJIANG   Zhejiang (help·info), formerly romanized as C...   
1  ZHEJIANG  The province's name derives from the Zhe River...   
2  ZHEJIANG  Zhejiang was the site of the Neolithic culture...   
3  ZHEJIANG  The area of modern Zhejiang was outside the ma...   
4  ZHEJIANG  Kuaiji Commandery was the initial power base f...   
5  ZHEJIANG  At the beginning of the Three Kingdoms era (22...   
6  ZHEJIANG  Zhejiang was part of the Wu during the Three K...   
7  ZHEJIANG  Despite the continuing prominence of Nanjing (...   
8  ZHEJIANG  Following the fall of Wu and the turmoil of th...   
9  ZHEJIANG  Zhejiang, as the heartland of the Jiangnan (Ya...   

                                          highlights  
0  Chekiang China Zhejiang Jiangsu Shanghai Anhui...  
1  the Zhe River Zhè Jiāng the Qiantang River Han...  
2  Zhejiang Neolithic Hemudu Liangzhu 2007 the Ya...  
3  Zhejiang Shang the second millennium BC the Hu... 

Keyword  \
15559                   1_MISCELLANEOUS   
15556                   1_MISCELLANEOUS   
15558                   1_MISCELLANEOUS   
15557                   1_MISCELLANEOUS   
15555  2008_SUMMER_OLYMPICS_TORCH_RELAY   
...                                 ...   
23                             ZHEJIANG   
22                             ZHEJIANG   
21                             ZHEJIANG   
29                             ZHEJIANG   
0                              ZHEJIANG   

                                                    Text  \
15559  After the Treaty of Utrecht (1713), Sicily was...   
15556  Although the two displayed great respect and a...   
15558  Eton has a long list of distinguished former p...   
15557  On August 24, 1673, Dutch captain Anthonio Col...   
15555  Two additional teams of 40 attendants each wil...   
...                                                  ...   
23     The province is traditionally known as the "La...   
22     Several political figures who served as Zhejia...   
21     The politics of Zhejiang is structured in a du...   
29     In mid-2015 the government of Zhejiang recogni...   
0       Zhejiang (help·info), formerly romanized as C...   

                                              highlights  
15559  the Treaty of Utrecht 1713 Sicily Savoia 1734 ...  
15556  two Harold C. Schonberg Chopin Liszt Liszt Lis...  
15558  Eton David Cameron 19th British Eton sixth New...  
15557  August 24, 1673 Dutch Anthonio Colve New York ...  
15555                             Two 40 Mainland China   
...                                                  ...  
23     the "Land of Fish and Rice Zhejiang China Zhou...  
22     Zhejiang Communist Party PRC Tan Zhenlin 1949-...  
21     Zhejiang Mainland China Zhejiang the People's ...  
29     mid-2015 Zhejiang more than twenty thousand Zh...  
0      Chekiang China Zhejiang Jiangsu Shanghai Anhui...  

[15560 rows x 3 columns]

In [ ]:
dfp.dropna(subset=['Text'], inplace = True)
print(dfp.loc[5501].iat[2])

the American Revolutionary War August 1776 Brooklyn Americans British North America Loyalist British Crown As many as 10,000 British British 1783 3,000 Nova Scotia England Caribbean 


In [ ]:
highlight=[]
for i in range (0, dfp.shape[0]):
  l=""
  text2= NER(dfp.loc[i].iat[1])
  for word in text2.ents:
    l=l+word.text+" "
  highlight.append(l)
print(highlight[0])



Chekiang China Zhejiang Jiangsu Shanghai Anhui Jiangxi Fujian the East China Sea Japan 


In [ ]:
print(highlight[5500])
print(len(highlight))

Manhattan John Peter Zenger 1735 North America 1754 Columbia University George II King's College in Lower Manhattan The Stamp Act Congress New York October 1765 the Sons of Liberty the next ten years British 
15560


In [ ]:
assert(len(highlight)==dfp.shape[0])
dfp.insert(2,'highlights',highlight)
dfp.to_csv('finalparagraphs.csv')

In [ ]:

wordlist=[dfp.loc[0].iat[0]]
i=1
k=1
while(i<dfp.shape[0]):
  if(dfp.loc[i].iat[0]!=dfp.loc[i-1].iat[0]):
    k=k+1
    wordlist.append(dfp.loc[i].iat[0])
  i=i+1
print(k)
wordlist = [element.upper() for element in wordlist]
print(wordlist)
print(dfp.shape)

363
['ZHEJIANG', 'YOUTUBE', 'YALE_UNIVERSITY', 'XBOX_360', 'WOOD', 'WINDOWS_8', 'WESTMINSTER_ABBEY', 'WAR_ON_TERROR', 'VIRGIL', 'VIDEOCONFERENCING', 'VALENCIA', 'VACUUM', 'USB', 'URANIUM', 'UNIVERSITY_OF_NOTRE_DAME', 'UNIVERSITY_OF_KANSAS', 'UNIVERSITY', 'UNIVERSAL_STUDIOS', 'UNITED_STATES_PRESIDENTIAL_ELECTION,_2004', 'UNITED_STATES_ARMY', 'UNITED_STATES_AIR_FORCE', 'UNITED_NATIONS_POPULATION_FUND', 'UNICODE', 'UMAYYAD_CALIPHATE', 'TUVALU', 'TURNER_CLASSIC_MOVIES', 'TUCSON,_ARIZONA', 'TRISTAN_DA_CUNHA', 'TREATY', 'TRANSLATION', 'TO_KILL_A_MOCKINGBIRD', 'TIME', 'THURINGIA', 'THEME', 'THE_SUN_(UNITED_KINGDOM)', 'THE_LEGEND_OF_ZELDA:_TWILIGHT_PRINCESS', 'THE_BRONX', 'THE_BLITZ', 'TEXTUAL_CRITICISM', 'TENNESSEE', 'TAJIKISTAN', 'SZLACHTA', 'SYMBIOSIS', 'SWITZERLAND', 'SWAZILAND', 'SUPREME_COURT', 'SUPER_NINTENDO_ENTERTAINMENT_SYSTEM', 'SUMER', 'STRASBOURG', 'STEVEN_SPIELBERG', 'STATES_OF_GERMANY', 'ST._JOHN%27S,_NEWFOUNDLAND_AND_LABRADOR', 'SPECTRE_(2015_FILM)', 'SPANISH_LANGUAGE_IN_THE_UN

In [ ]:

start=[0]
end=[]
for i in range(1, dfp.shape[0]):
  if(dfp.loc[i].iat[0]!=dfp.loc[i-1].iat[0]):
    end.append(i)
    start.append(i)
end.append(dfp.shape[0])
print(wordlist)
print(start)
print(end)
assert(len(wordlist)==len(start))
assert(len(end)==len(start))


['ZHEJIANG', 'YOUTUBE', 'YALE_UNIVERSITY', 'XBOX_360', 'WOOD', 'WINDOWS_8', 'WESTMINSTER_ABBEY', 'WAR_ON_TERROR', 'VIRGIL', 'VIDEOCONFERENCING', 'VALENCIA', 'VACUUM', 'USB', 'URANIUM', 'UNIVERSITY_OF_NOTRE_DAME', 'UNIVERSITY_OF_KANSAS', 'UNIVERSITY', 'UNIVERSAL_STUDIOS', 'UNITED_STATES_PRESIDENTIAL_ELECTION,_2004', 'UNITED_STATES_ARMY', 'UNITED_STATES_AIR_FORCE', 'UNITED_NATIONS_POPULATION_FUND', 'UNICODE', 'UMAYYAD_CALIPHATE', 'TUVALU', 'TURNER_CLASSIC_MOVIES', 'TUCSON,_ARIZONA', 'TRISTAN_DA_CUNHA', 'TREATY', 'TRANSLATION', 'TO_KILL_A_MOCKINGBIRD', 'TIME', 'THURINGIA', 'THEME', 'THE_SUN_(UNITED_KINGDOM)', 'THE_LEGEND_OF_ZELDA:_TWILIGHT_PRINCESS', 'THE_BRONX', 'THE_BLITZ', 'TEXTUAL_CRITICISM', 'TENNESSEE', 'TAJIKISTAN', 'SZLACHTA', 'SYMBIOSIS', 'SWITZERLAND', 'SWAZILAND', 'SUPREME_COURT', 'SUPER_NINTENDO_ENTERTAINMENT_SYSTEM', 'SUMER', 'STRASBOURG', 'STEVEN_SPIELBERG', 'STATES_OF_GERMANY', 'ST._JOHN%27S,_NEWFOUNDLAND_AND_LABRADOR', 'SPECTRE_(2015_FILM)', 'SPANISH_LANGUAGE_IN_THE_UNITED

In [ ]:
df = pd.DataFrame(list(zip(wordlist, start,end)), columns=['Keyword', 'Start','End'])
print(df.shape)
print(df.head(10))
df.to_csv('Range.csv')

(363, 3)
             Keyword  Start  End
0           ZHEJIANG      0   38
1            YOUTUBE     38   72
2    YALE_UNIVERSITY     72  118
3           XBOX_360    118  144
4               WOOD    144  213
5          WINDOWS_8    213  261
6  WESTMINSTER_ABBEY    261  307
7      WAR_ON_TERROR    307  338
8             VIRGIL    338  361
9  VIDEOCONFERENCING    361  382


In [ ]:
RANGE={}
for i in range(0,len(wordlist)):
  RANGE.update({f'{i}': Ran(start[i],end[i])})
# print(RANGE['301'])

12730-12790


In [ ]:
import torch
from sentence_transformers import SentenceTransformer, util

# Load the pre-trained model
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [ ]:
!pip install safetensors huggingface_hub
!pip install gradio
import gradio as gr

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 61.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.9/315.9 kB 38.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.5/142.5 kB 22.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 63.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.2/47.2 kB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 9.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 20.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 10.0 MB/

In [ ]:
import torch
from safetensors.torch import save_file
from safetensors import safe_open

In [ ]:
def Ran(num1,num2):
  return (f"{num1}-{num2}")

In [ ]:


text = "This is another example? Notice: 'it removes /punctuation.'/"
tokens = tokenizer.tokenize(text)
print(tokens)

['This', 'is', 'another', 'example', 'Notice', 'it', 'removes', 'punctuation']


Now we convert all keywords to tensors, and similarly, all 15000+ training sentences as well. I observed that initially model was taking too mcuh time because it was transforming multiple sentences to tensors which take too much time on CPU. On T4 GPU, It hardly takes 3 minutes to do all tensor transformations

In [ ]:
i=0
tensors={}
while(i<len(wordlist)):
  # if(dfp.loc[i].iat[1].dtype !=string)
  V=model.encode(wordlist[i],convert_to_tensor=True)
  tensors.update({f'{i}': V})
  i=i+1
print(len(tensors))
print(tensors['0'])
V=model.encode("ZHEJIANG",convert_to_tensor=True)
print(V)
assert(torch.equal(tensors['0'],V))
save_file(tensors, "model.mapkeywordsfinal")

363
tensor([-4.4479e-03,  6.1240e-02,  6.9212e-02,  9.0715e-03, -5.7058e-02,
        -4.5169e-02,  6.5377e-02, -2.9240e-02, -1.3880e-02,  1.3226e-02,
         4.2528e-02, -9.9488e-02,  1.1509e-01, -2.1972e-02,  2.8137e-02,
         2.2371e-02,  2.6052e-02, -5.9325e-02,  7.3657e-02, -1.1208e-01,
        -5.3358e-02,  6.9447e-02,  4.8235e-02,  1.9215e-02, -9.4715e-03,
        -2.2734e-02,  1.0000e-02,  6.9510e-02,  2.5109e-02, -7.3920e-02,
        -1.2872e-02,  6.9723e-02,  6.7461e-02, -1.6818e-02,  4.6295e-02,
         5.5002e-02,  4.4357e-02, -6.6529e-02, -1.2197e-01, -1.1507e-02,
        -1.5367e-02,  4.8024e-02,  5.2704e-02, -2.0461e-02,  2.4188e-02,
         6.4826e-02,  3.8616e-02, -2.9412e-02,  2.5544e-02, -1.0839e-01,
         2.7523e-02,  4.4821e-03, -9.8957e-03,  3.0650e-02,  6.7064e-02,
         7.3254e-02, -6.8204e-04, -9.0405e-03, -2.7329e-04, -6.7920e-03,
        -5.4489e-02,  3.6757e-02, -4.2755e-02, -2.1204e-02,  6.1179e-02,
         5.5608e-02, -8.9889e-03,  4.2270e-02, 

In [ ]:
#There used to be constant error at a row close to 5501, due to nan in text column, Hence the number 5501
#I create a dictionary, which maps each sentence to its respective tensor by the index value of sentence.
print(dfp.loc[5501].iat[1])
i=0
TENSORS={}
while(i<dfp.shape[0]):
  # if(dfp.loc[i].iat[1].dtype !=string)
  V=model.encode(dfp.loc[i].iat[1],convert_to_tensor=True)
  TENSORS.update({f'{i}': V})
  i=i+1
print(len(TENSORS))
print(TENSORS['100'])
V=model.encode(dfp.loc[100].iat[1],convert_to_tensor=True)
print(V)
assert(torch.equal(TENSORS['100'],V))
save_file(TENSORS, "model.mapsentencesfinal")

The Battle of Long Island, the largest battle of the American Revolutionary War, was fought in August 1776 entirely within the modern-day borough of Brooklyn. After the battle, in which the Americans were defeated, leaving subsequent smaller armed engagements following in its wake, the city became the British military and political base of operations in North America. The city was a haven for Loyalist refugees, as well as escaped slaves who joined the British lines for freedom newly promised by the Crown for all fighters. As many as 10,000 escaped slaves crowded into the city during the British occupation. When the British forces evacuated at the close of the war in 1783, they transported 3,000 freedmen for resettlement in Nova Scotia. They resettled other freedmen in England and the Caribbean.
15560
tensor([ 2.6533e-02, -3.4082e-02,  9.5425e-03,  2.1739e-02,  7.8999e-03,
        -5.8516e-02, -1.5255e-01, -1.0220e-01, -3.6525e-02, -5.4340e-02,
         1.5006e-02,  3.1112e-02,  5.2682e

In [ ]:
V=model.encode(dfp.loc[100].iat[1],convert_to_tensor=True)
print(V)

tensor([ 2.6533e-02, -3.4082e-02,  9.5425e-03,  2.1739e-02,  7.8999e-03,
        -5.8516e-02, -1.5255e-01, -1.0220e-01, -3.6525e-02, -5.4340e-02,
         1.5006e-02,  3.1112e-02,  5.2682e-02, -4.4367e-02, -2.5317e-02,
        -1.6996e-02, -7.2400e-02,  6.5373e-02,  7.0579e-02,  3.7209e-02,
        -3.7283e-02, -1.1250e-02, -2.3932e-02,  1.1332e-02,  1.4247e-02,
         2.4730e-02,  5.5483e-02, -7.5789e-03, -1.7507e-02, -4.7392e-02,
        -6.4816e-03, -1.6264e-02,  2.6302e-02, -1.7018e-02,  2.2376e-02,
         7.0980e-03,  4.0258e-03,  4.2530e-02,  1.5442e-02, -2.4247e-02,
        -6.4497e-02,  6.5362e-02,  7.0930e-02,  4.5769e-02, -9.0235e-02,
        -5.2919e-02, -2.9017e-02, -1.1582e-01, -2.7880e-03,  1.2329e-02,
         1.5144e-02, -1.6268e-02,  3.5948e-02,  3.2803e-02,  1.6618e-02,
         1.1640e-01,  2.8405e-02, -2.3777e-02, -2.5268e-02,  1.7265e-02,
         5.7018e-02,  8.3251e-03, -5.5917e-02, -3.4288e-02, -6.4581e-02,
         5.7991e-02, -4.2123e-02,  7.4618e-02,  6.9

In [ ]:
#Another dictionary for tensors with important keywords
print(dfp.loc[5501].iat[2])
i=0
TENsoRS={}
while(i<dfp.shape[0]):
  # if(dfp.loc[i].iat[1].dtype !=string)
  V=model.encode(dfp.loc[i].iat[2],convert_to_tensor=True)
  TENsoRS.update({f'{i}': V})
  i=i+1
print(len(TENsoRS))
print(TENsoRS['100'])
V=model.encode(dfp.loc[100].iat[2],convert_to_tensor=True)
print(V)
assert(torch.equal(TENsoRS['100'],V))
save_file(TENsoRS, "model.maphighlightsfinal")

the American Revolutionary War August 1776 Brooklyn Americans British North America Loyalist British Crown As many as 10,000 British British 1783 3,000 Nova Scotia England Caribbean 
15560
tensor([-3.0534e-02,  5.7113e-03,  3.0307e-02, -4.2934e-03,  1.3311e-02,
        -3.8011e-02, -1.3683e-01, -7.9374e-02, -1.0319e-02,  3.0115e-02,
         5.7170e-03, -2.4671e-02,  1.0495e-02, -2.0071e-02, -4.7902e-02,
         3.1849e-02, -6.2979e-02,  6.1002e-02,  3.3449e-02, -6.6979e-04,
        -4.0316e-02, -2.8440e-02, -1.2312e-02,  2.5848e-02, -2.5093e-02,
         2.7895e-02,  5.2179e-02, -2.5034e-02, -3.2892e-02, -5.9367e-02,
        -6.2677e-02, -2.4247e-02, -6.7243e-04, -1.5180e-02, -9.1367e-03,
        -4.2286e-02,  5.1904e-02,  3.4889e-02,  5.9226e-02,  8.6919e-05,
        -8.8206e-02,  1.1851e-02,  3.9754e-02,  9.6921e-02, -7.3895e-02,
        -6.0149e-02, -1.2640e-02, -5.6628e-02,  3.3690e-03, -1.0771e-03,
        -4.5023e-03, -7.1352e-03, -2.8182e-02,  1.5191e-02, -1.5613e-02,
        

# Modelling (where code for output begins)

Using the files I've uploaded in the google drive with this notebook, we can immediately begin training over texts as tensors and work with this NLP problem


In [1]:
!pip install transformers
!pip install torch
!pip install sentence-transformers
!pip install gradio
!pip install safetensors huggingface_hub
import gradio as gr
import numpy as np
import pandas as pd
import spacy
from spacy import displacy
import torch
from safetensors.torch import save_file
from safetensors import safe_open
from sentence_transformers import SentenceTransformer, util
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')
# Load the pre-trained model
model = SentenceTransformer('all-MiniLM-L6-v2')
NER = spacy.load("en_core_web_sm")

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [2]:
def remove_punctuations(texy):
  tokeny=tokenizer.tokenize(texy)
  return tokeny

In [3]:
dfp=pd.read_csv("finalparagraphs.csv")
dfp.drop(columns=dfp.columns[0], axis=1, inplace=True)
print(dfp.head(10))
dfq=pd.read_csv("finalqueries.csv")
print(dfq.head(10))

    Keyword                                               Text  \
0  ZHEJIANG   Zhejiang (help·info), formerly romanized as C...   
1  ZHEJIANG  The province's name derives from the Zhe River...   
2  ZHEJIANG  Zhejiang was the site of the Neolithic culture...   
3  ZHEJIANG  The area of modern Zhejiang was outside the ma...   
4  ZHEJIANG  Kuaiji Commandery was the initial power base f...   
5  ZHEJIANG  At the beginning of the Three Kingdoms era (22...   
6  ZHEJIANG  Zhejiang was part of the Wu during the Three K...   
7  ZHEJIANG  Despite the continuing prominence of Nanjing (...   
8  ZHEJIANG  Following the fall of Wu and the turmoil of th...   
9  ZHEJIANG  Zhejiang, as the heartland of the Jiangnan (Ya...   

                                          highlights  
0  Chekiang China Zhejiang Jiangsu Shanghai Anhui...  
1  the Zhe River Zhè Jiāng the Qiantang River Han...  
2  Zhejiang Neolithic Hemudu Liangzhu 2007 the Ya...  
3  Zhejiang Shang the second millennium BC the Hu... 

In [4]:
dfr=pd.read_csv("Range.csv")
dfr.drop(columns=dfr.columns[0], axis=1, inplace=True)
print(dfr.head(10))
wordlist=[]
for i in range(dfr.shape[0]):
  wordlist.append(dfr.loc[i].iat[0])
print(wordlist)

             Keyword  Start  End
0           ZHEJIANG      0   38
1            YOUTUBE     38   72
2    YALE_UNIVERSITY     72  118
3           XBOX_360    118  144
4               WOOD    144  213
5          WINDOWS_8    213  261
6  WESTMINSTER_ABBEY    261  307
7      WAR_ON_TERROR    307  338
8             VIRGIL    338  361
9  VIDEOCONFERENCING    361  382
['ZHEJIANG', 'YOUTUBE', 'YALE_UNIVERSITY', 'XBOX_360', 'WOOD', 'WINDOWS_8', 'WESTMINSTER_ABBEY', 'WAR_ON_TERROR', 'VIRGIL', 'VIDEOCONFERENCING', 'VALENCIA', 'VACUUM', 'USB', 'URANIUM', 'UNIVERSITY_OF_NOTRE_DAME', 'UNIVERSITY_OF_KANSAS', 'UNIVERSITY', 'UNIVERSAL_STUDIOS', 'UNITED_STATES_PRESIDENTIAL_ELECTION,_2004', 'UNITED_STATES_ARMY', 'UNITED_STATES_AIR_FORCE', 'UNITED_NATIONS_POPULATION_FUND', 'UNICODE', 'UMAYYAD_CALIPHATE', 'TUVALU', 'TURNER_CLASSIC_MOVIES', 'TUCSON,_ARIZONA', 'TRISTAN_DA_CUNHA', 'TREATY', 'TRANSLATION', 'TO_KILL_A_MOCKINGBIRD', 'TIME', 'THURINGIA', 'THEME', 'THE_SUN_(UNITED_KINGDOM)', 'THE_LEGEND_OF_ZELDA:_T

In [5]:
tensors_wordlist = {}
with safe_open("model.mapkeywordsfinal", framework="pt", device=0) as f:
    for k in f.keys():
        tensors_wordlist[k] = f.get_tensor(k) # loads the full tensor given a key

print(tensors_wordlist[list(tensors_wordlist.keys())[0]])
A=list(tensors_wordlist.keys())

print(A)


tensor([-4.4479e-03,  6.1240e-02,  6.9212e-02,  9.0715e-03, -5.7058e-02,
        -4.5169e-02,  6.5377e-02, -2.9240e-02, -1.3880e-02,  1.3226e-02,
         4.2528e-02, -9.9488e-02,  1.1509e-01, -2.1972e-02,  2.8137e-02,
         2.2371e-02,  2.6052e-02, -5.9325e-02,  7.3657e-02, -1.1208e-01,
        -5.3358e-02,  6.9447e-02,  4.8235e-02,  1.9215e-02, -9.4715e-03,
        -2.2734e-02,  1.0000e-02,  6.9510e-02,  2.5109e-02, -7.3920e-02,
        -1.2872e-02,  6.9723e-02,  6.7461e-02, -1.6818e-02,  4.6295e-02,
         5.5002e-02,  4.4357e-02, -6.6529e-02, -1.2197e-01, -1.1507e-02,
        -1.5367e-02,  4.8024e-02,  5.2704e-02, -2.0461e-02,  2.4188e-02,
         6.4826e-02,  3.8616e-02, -2.9412e-02,  2.5544e-02, -1.0839e-01,
         2.7523e-02,  4.4821e-03, -9.8957e-03,  3.0650e-02,  6.7064e-02,
         7.3254e-02, -6.8204e-04, -9.0405e-03, -2.7329e-04, -6.7920e-03,
        -5.4489e-02,  3.6757e-02, -4.2755e-02, -2.1204e-02,  6.1179e-02,
         5.5608e-02, -8.9889e-03,  4.2270e-02, -4.9

In [7]:
TENSORS_LIST = {}
with safe_open("model.mapsentencesfinal", framework="pt", device=0) as f:
    for k in f.keys():
        TENSORS_LIST[k] = f.get_tensor(k) # loads the full tensor given a key

print(TENSORS_LIST[list(TENSORS_LIST.keys())[0]])
print(TENSORS_LIST['100'])

B=list(TENSORS_LIST.keys())

print(B)


tensor([ 6.4940e-02,  4.5494e-02,  8.2786e-02,  4.8105e-03, -4.5533e-03,
        -5.3459e-02,  1.0663e-01, -1.7070e-02,  1.5464e-02, -6.0476e-02,
         8.5628e-02, -7.6622e-02,  8.6906e-02, -5.2563e-02,  2.6931e-02,
         2.4602e-02,  1.4652e-02, -4.2590e-02,  9.5942e-03, -9.4953e-02,
        -4.7847e-02,  3.3231e-02,  7.8426e-02, -1.4937e-02, -5.8611e-02,
        -5.0770e-02,  2.8686e-02,  8.9487e-02,  5.2470e-03,  2.2774e-02,
        -2.9692e-02,  7.6813e-02, -1.4379e-02,  5.0774e-02,  4.7927e-02,
         9.0034e-02,  3.9867e-02, -4.0591e-02, -7.1735e-02, -1.1553e-02,
        -3.8407e-02,  6.5083e-02,  1.8936e-02,  6.0726e-02,  1.9178e-02,
         2.7316e-02,  7.4674e-02, -7.6286e-02, -1.9019e-02, -1.4638e-01,
         4.0145e-02, -1.2007e-02, -5.5697e-03,  6.5170e-02,  2.9594e-02,
         8.2663e-02,  2.2322e-02,  3.3839e-02, -2.9630e-02, -8.8601e-04,
        -5.9869e-02, -2.4850e-02,  4.0113e-02, -2.5483e-02,  2.8928e-02,
         7.8073e-02,  2.5126e-02,  2.8954e-02, -3.1

In [8]:
V=model.encode(dfp.loc[100].iat[1],convert_to_tensor=True)
print(V)
print(dfp.loc[100].iat[1])
assert(torch.equal(TENSORS_LIST['100'],V))
print("Successful storage of tensors !")

tensor([ 2.6533e-02, -3.4082e-02,  9.5425e-03,  2.1739e-02,  7.8999e-03,
        -5.8516e-02, -1.5255e-01, -1.0220e-01, -3.6525e-02, -5.4340e-02,
         1.5006e-02,  3.1112e-02,  5.2682e-02, -4.4367e-02, -2.5317e-02,
        -1.6996e-02, -7.2400e-02,  6.5373e-02,  7.0579e-02,  3.7209e-02,
        -3.7283e-02, -1.1250e-02, -2.3932e-02,  1.1332e-02,  1.4247e-02,
         2.4730e-02,  5.5483e-02, -7.5789e-03, -1.7507e-02, -4.7392e-02,
        -6.4816e-03, -1.6264e-02,  2.6302e-02, -1.7018e-02,  2.2376e-02,
         7.0980e-03,  4.0258e-03,  4.2530e-02,  1.5442e-02, -2.4247e-02,
        -6.4497e-02,  6.5362e-02,  7.0930e-02,  4.5769e-02, -9.0235e-02,
        -5.2919e-02, -2.9017e-02, -1.1582e-01, -2.7880e-03,  1.2329e-02,
         1.5144e-02, -1.6268e-02,  3.5948e-02,  3.2803e-02,  1.6618e-02,
         1.1640e-01,  2.8405e-02, -2.3777e-02, -2.5268e-02,  1.7265e-02,
         5.7018e-02,  8.3251e-03, -5.5917e-02, -3.4288e-02, -6.4581e-02,
         5.7991e-02, -4.2123e-02,  7.4618e-02,  6.9

In [9]:
TENSORS_list = {}
with safe_open("model.maphighlightsfinal", framework="pt", device=0) as f:
    for k in f.keys():
        TENSORS_list[k] = f.get_tensor(k) # loads the full tensor given a key

print(TENSORS_list[list(TENSORS_list.keys())[0]])
print(TENSORS_list['100'])

B=list(TENSORS_list.keys())

print(B)

tensor([-2.9493e-03,  8.7767e-02,  7.1519e-02,  2.9685e-02, -9.0545e-03,
        -5.9495e-02,  8.0025e-02,  9.6422e-03, -6.2630e-02, -5.8104e-02,
         7.3541e-02, -9.7855e-02, -5.9075e-04, -1.3991e-02, -2.5834e-02,
         3.5705e-02, -3.4700e-02,  3.8182e-02, -3.6933e-02, -8.1621e-02,
        -8.8855e-02, -5.3446e-02,  6.8502e-02, -2.8680e-02, -8.7967e-02,
        -3.3424e-02,  3.3686e-02,  8.2140e-02,  4.0776e-02, -1.2873e-02,
        -9.4758e-02,  1.1993e-01,  4.3042e-02,  7.3769e-02,  5.2543e-02,
         7.2286e-02, -2.9045e-02, -2.5855e-02,  1.9030e-02,  3.7287e-02,
        -1.6865e-02,  2.2279e-02,  7.4054e-02,  7.2980e-02, -7.3629e-03,
        -2.1589e-02,  2.9129e-02, -9.4301e-02, -4.9833e-02, -5.0295e-02,
         3.2223e-02, -2.0311e-04, -5.7904e-02,  2.1022e-02, -5.1052e-02,
         3.4412e-02, -4.3021e-03,  3.8728e-02,  5.2363e-03, -5.9401e-02,
        -3.1055e-02, -6.1961e-03,  6.6703e-03, -6.3663e-02,  7.4151e-02,
         7.0801e-02, -3.1276e-02,  3.0852e-02, -7.0

In [10]:
V=model.encode(dfp.loc[100].iat[2],convert_to_tensor=True)
assert(torch.equal(TENSORS_list['100'],V))
print("Yet again Successful storage of tensors !")

Yet again Successful storage of tensors !


In [11]:
P=[]
Q=[]
R=[]
print(len(list(TENSORS_LIST.keys())))
for i in range(0,len(list(TENSORS_LIST.keys())) ):
  R.append(TENSORS_list[f'{i}'])
  Q.append(TENSORS_LIST[f'{i}'])
for i in range(0,len(list(tensors_wordlist.keys())) ):
  P.append(tensors_wordlist[f'{i}'])
print(len(Q))
X=torch.stack(P)
Y=torch.stack(Q)
Z=torch.stack(R)
print(X.shape)
print(Y.shape)
print(Z.shape)

15560
15560
torch.Size([363, 384])
torch.Size([15560, 384])
torch.Size([15560, 384])


In [12]:
def get_match(query_embedding, top_k=5):
    #We will convert paragraphs and queries to simple vectors for easier comparision
    # paragraphs_embeddings = model.encode(paragraphs, convert_to_tensor=True)

    # Cosine similarities between the query and each paragraph are computed
    cosine_scores = util.pytorch_cos_sim(query_embedding, X)[0]

    # Get the top_k (5) most relevant paragraphs
    top_results = torch.topk(cosine_scores, k=top_k)

    # Extract the paragraphs and scores
    relevant_paragraphs = [(idx, score.item()) for idx, score in zip(top_results.indices, top_results.values)]
    ids=[]
    for i in range(0,top_k):
      S=f"{relevant_paragraphs[i]}"
      S=remove_punctuations(S)
      # print(S)
      ids.append(S[1])
    return ids


In [13]:
def get_relevant_paragraphs(query_embedding, Tensor1, Tensor2, index,top_k=5):
    #We will convert paragraphs and queries to simple vectors for easier comparision
    # query_embedding = model.encode(query, convert_to_tensor=True)
    # paragraphs_embeddings = model.encode(paragraphs, convert_to_tensor=True)

    # Cosine similarities between the query and each paragraph are computed
    cosine_scores = util.pytorch_cos_sim(query_embedding, Tensor1)[0] + util.pytorch_cos_sim(query_embedding, Tensor2)[0]

    # Get the top_k (5) most relevant paragraphs
    top_results = torch.topk(cosine_scores, k=top_k)

    # Extract the paragraphs and scores
    relevant_paragraphs = [(idx, score.item()) for idx, score in zip(top_results.indices, top_results.values)]
    ids=[]
    for i in range(0,top_k):
      S=f"{relevant_paragraphs[i]}"
      S=remove_punctuations(S)
      # print(S)
      ids.append(S[1])
    numbers=[]
    lines=[]
    for i in (ids):
      numbers.append(index[int(i)])
    for i in (numbers):
      lines.append(dfp.loc[int(i)].iat[1])

    return lines

In [14]:
def get5lines(query="Nintendo Entertainment System discontinued "):

  q = model.encode(query, convert_to_tensor=True)
  BestKeywords= get_match(q, top_k=2)
  W1 = []
  W2 = []
  index=[]
  for i in BestKeywords:
    print(wordlist[int(i)])
    for j in range (dfr.loc[int(i)].iat[1],dfr.loc[int(i)].iat[2]):
      W1.append(Y[j])
      W2.append(Z[j])
      index.append(j)
  M=torch.stack(W1)
  N=torch.stack(W2)
# print(Z.shape)
  LINES=get_relevant_paragraphs(q, M,N,index)
  return (LINES)

In [15]:
print(wordlist[46])

SUPER_NINTENDO_ENTERTAINMENT_SYSTEM


In [16]:
paragraph = get5lines("Bill Clinton")
for i in (paragraph):
  print(i)

BILL_%26_MELINDA_GATES_FOUNDATION
JOHN_KERRY
In his 2004 presidential campaign, Kerry criticized George W. Bush for the Iraq War. He and his running mate, North Carolina Senator John Edwards, lost the election, finishing 35 electoral votes behind Bush and Vice President Dick Cheney. Kerry returned to the Senate, becoming Chairman of the Senate Committee on Small Business and Entrepreneurship in 2007 and then of the Foreign Relations Committee in 2009. In January 2013, Kerry was nominated by President Barack Obama to succeed outgoing Secretary of State Hillary Clinton and then confirmed by the U.S. Senate, assuming the office on February 1, 2013.
On December 15, 2012, several news outlets reported that President Barack Obama would nominate Kerry to succeed Hillary Clinton as Secretary of State, after Susan Rice, widely seen as Obama's preferred choice, withdrew her name from consideration citing a politicized confirmation process following criticism of her response to the 2012 Benghazi 

In [17]:
# def getanswer(query):
#   sample=get5lines(query)
# Continued in 2nd notebook

In [19]:
# Not used here
import re
string = "Rhino123.45Python987.654 is amazing. I like him"
strChar = re.findall(r'[0-9.]+|\D',string)
print (strChar)

['R', 'h', 'i', 'n', 'o', '123.45', 'P', 'y', 't', 'h', 'o', 'n', '987.654', ' ', 'i', 's', ' ', 'a', 'm', 'a', 'z', 'i', 'n', 'g', '.', ' ', 'I', ' ', 'l', 'i', 'k', 'e', ' ', 'h', 'i', 'm']


In [20]:
gr.themes.builder()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://5704660bb27ca403ba.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


In [21]:
# def greet(name):
#     return "Hello " + name + "!"
# demo =
with gr.Blocks(theme=gr.themes.Default(primary_hue="emerald", neutral_hue="green")) as demo:
    gr.Interface(fn=get5lines, inputs="textbox", outputs=['text','text','text','text','text'])

if __name__ == "__main__":
    demo.launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://843ee4d4a126e9e857.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


In [ ]:
# import random
# def random_response(message, history):
#     return random.choice(["Yes", "No"])

# with gr.Blocks(theme=gr.themes.Default(primary_hue="pink", neutral_hue="red")) as demo2:
#     demo2 = gr.ChatInterface(random_response)


# if __name__ == "__main__":
#     demo0.launch()

NameError: name 'demo0' is not defined